### ISSUE TITLE
In firefox, an iframe with data binded url refreshes every single render

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#398]
In Firefox, an iframe with data binded url refreshes every single render.

Causes extreme lag.

**Comment by lhorie** [comment]
Can you provide a jsfiddle demonstrating the issue?

**Comment by kvanberendonck** [comment]
Actually, not at the moment. jsfiddle does something strange to iframes, but when I get time I'll do a locally runnable example.

**Comment by kvanberendonck** [comment]
At work today found there is a VDOM corruption/refresh thing going on for the last element of most arrays passed to mithril in our app. This could be related to the other ticked about cursor blinking too..

Will update with test case

**Comment by kvanberendonck** [comment]
Removing an element from the end of the sandwiched array seems to be what triggered it, we think.

**Comment by lhorie** [comment]
FYI, I just fixed #424, which was a bug related to keys. It may have fixed this issue

**Comment by kvanberendonck** [comment]
I will attempt to push the team to upgrade our version of mithril to latest, but usually there's quite a large turnaround involved as 1) a lot breaks generally in the process and 2) as the product works it tends to be lower priority. Sorry, but I'll hopefully have some news related to this soon.

**Comment by kvanberendonck** [comment]
@lhorie  I tested this with 1.30 and it didn't solve the problem unfortunately.

**Comment by lhorie** [comment]
I was able to reproduce with the following snippet:

```javascript
var show = false

m.module(document.body, {
	controller: function() {
		this.rendered = 0
		setInterval(function() {m.redraw()}, 100)
	},
	view: function(ctrl) {
		return [
			m("div", {key: 1, onclick: function() {show = !show}}, "click"),
			show ? [m("div"), m("div")] : m("div"),
			m("iframe", {key: 2, src: "something.html"})
		]
	}
})
```

Fixed that case in origin/next

**Comment by kvanberendonck** [comment]
Thanks Leo!
