### ISSUE TITLE
Rendering is bugged

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#524]
http://codepen.io/farzher/pen/LEaraN?editors=101

Spam click the checkbox.
Not only does it keep rendering more "bugs" at the bottom of the screen.
It also sometimes randomizes the order in which the links are rendered!

**Comment by saniko** [comment]
I have similar problem of duplicating dom elements upon click, but it happens only in last version 1.32, if i use 1.30, all is OK.
@farzher what version are you running?

**Comment by farzher** [comment]
You're right. Neither issue exists in 0.30.
The issues exist in 0.31+

**Comment by lhorie** [comment]
Yep. Reproducible. Will take a look

**Comment by lhorie** [comment]
fixed in origin/next

**Comment by saniko** [comment]
is this fixed in 1.33?
still having the same problem

**Comment by StephanHoyer** [comment]
Also still having some issues... try to create a fiddle, but currenlty can't boil it down to a simple use case.

**Comment by lhorie** [comment]
Yeah, sorry guys. 0.1.31 made a change in the rendering engine, and it looks like it introduced a few regressions. I'm looking into them and pushing out new releases as I find them

**Comment by lhorie** [comment]
update: I pushed another fix to the next branch
